const pkg = require('../../package.json');

const strings = {
  ASSOCIATION: 'Verband',
  CONFIRM: 'Bestätigen',
  AWAY: 'Gast',
  HOME: 'Heim',
  CLUB: 'Verein',
  CONTACT: 'Kontakt',
  HOME_TABLE: 'Heimtisch',
  HOME_MATCH_TIME: 'Heimspielzeit',
  HOME_VENUE: 'Heimspielort',
  OPEN_VENUE: 'Spielort anzeigen',
  CHANGE_MATCH_DATETIME: 'Termin ändern',
  DATETIME_SUGGESTIONS: 'Terminvorschläge',
  SUGGEST_DATETIMES: 'Termine vorschlagen',
  SELECT_NEXT_DATETIMTE: 'Weiteren Termin auswählen',
  FIRST_MATCH: 'Hinspiel',
  MAIL_APP_NOT_FOUND: 'Keine E-Mail App gefunden.',
  MAPS_APP_NOT_FOUND: 'Keine Karten App gefunden.',
  NAME: 'Name',
  PHONE_APP_NOT_FOUND: 'Keine Telefon App gefunden.',
  PLAYER: 'Spieler',
  GROUP: 'Gruppe',
  GROUPS: 'Gruppen',
  LEAGUES: 'Gruppen',
  WEEKDAYS: [
    'Sonntag',
    'Montag',
    'Dienstag',
    'Mittwoch',
    'Donnerstag',
    'Freitag',
    'Samstag',
  ],
  SCORE_BUTTON_TEXT: [
    'Ergebnis vorschlagen',
    'Ergebnis vorgeschlagen',
    'Ergebnis akzeptieren',
  ],
  TIME_AT: 'um',
  DOT_POSITION: '. Platz',
  POSITION: 'Platz',
  SELECT_GROUP: 'Gruppe wählen',
  SELECT_GROUPS: 'Gruppen wählen',
  SELECT_TEAM: 'Team wählen',
  LOGIN: 'Anmelden',
  LOGOUT: 'Abmelden',
  LOGIN_INFO:
    'Zugangsdaten für das Liga-Tool.\nWenn diese nicht eingetragen werden, können keine Spiele eingetragen werden.',
  LOGIN_ERROR: 'Fehler beim Anmelden. Überprüfe deine Zugangsdaten.',
  USERNAME: 'Benutzername',
  PASSWORD: 'Passwort',
  CANCEL: 'Abbrechen',
  DELETE: 'Löschen',
  SAVE: 'Speichern',
  SKIP: 'Überspringen',
  MATCHES: 'Begegnungen',
  STATISTICS: 'Statistiken',
  STATISTIC: 'Statistik',
  MY_TEAM: 'Mein Team',
  SECOND_HALFTIME: '2. Halbzeit',
  CLASSIFICATION: 'Einstufung',
  SET_POINTS_RATE: 'Spielpunkte Quote',
  NATIONAL_NUMBER: 'Nationale Spielernummer',
  INTERNATIONAL_NUMBER: 'Internationale Spielernummer',
  WIN: 'Sieg',
  WIN_POSTFIX: 'e',
  DRAW: 'Unentschieden',
  DRAW_POSTFIX: '',
  LOST: 'Niederlage',
  LOST_POSTFIX: 'n',
  APP_VERSION:
    'App-Version ' + pkg.version.substring(0, pkg.version.length - 2),
  CACHE_INFORMATION:
    'Teamlogos und Spielerbilder werden Lokal gespeichert, um das Datenvolumen zu schonen. Sollten mal nicht die aktuellsten Bilder angezeigt werden, kann hier der Speicher gelöscht werden und die Bilder werden neu geladen.',
  INFORMATION: 'Informationen',
  CLEAR_IMAGE_CACHE: 'Bilder-Cache leeren',
  COMPETITIVE_INDEX: 'Leistungsindex',
  COMPETITIVE_INDEX_SHORT: 'LI',
  GAMES: 'Spiele',
  GAMES_SHORT: 'Sp.',
  GOALS: 'Tore',
  MATCH: 'Begegnung',
  ENTER_ACCESS_DATA: 'Zugangsdaten eingeben',
  USER_DATA: 'Benutzerdaten',
  NOTIFICATIONS: 'Benachrichtigungen',
  NOTIFICATION_LIVE: 'Live-Zwischenergebnis',
  NOTIFICATION_END: 'Endstand',
  NOTIFICATION_MATCH_DATE: 'Termin Änderungen',
  NOTIFICATION_SOUND: 'Sound/Vibration',
  OVERVIEW: 'Übersicht',
  PAST_MATCHES: 'Vergangene',
  NEXT_MATCHES: 'Kommende',
  PLAYER_INFO: 'Spieler-Info',
  POINTS_SHORT: 'Pkt.',
  RATE_SHORT: 'Q',
  SELECT: 'Bitte wählen',
  SELECT_PLAYER: 'Spieler wählen',
  INSERT_SCORE: 'Ergebnis eintragen',
  SETS: 'Sätze',
  SETTINGS: 'Einstellungen',
  SO_FAR: 'bisher ',
  TABLE: 'Tabelle',
  TEAM: 'Team',
  TEAM_INFO: 'Team-Info',
  TODAY: 'Heute',
  RESULT: 'Ergebnis',
  DOT_SET: '. Satz',
  SEARCH: 'Suche',
  SEARCH_PLACEHOLDER: 'Spieler, Team',
};

export default strings;
