export default {
  overview: 'Übersicht',
  my_team: 'Mein Team',
  leagues: 'Gruppen',
  settings: 'Einstellungen',
  notifications: 'Benachrichtigungen',
  today: 'Heute',
  next: 'Kommende',
  played: 'Vergangene',
  team: 'Team',
  home: 'Heim',
  away: 'Gast',
  table: 'Tabelle',
  user_data: 'Benutzerdaten',
  login: 'Anmelden',
  logout: 'Abmelden',
  skip: 'Überspringen',
  score_live: 'Live-Zwsichenergebnis',
  score_end: 'Endstand',
  select_leagues: 'Gruppen wählen',
  information: 'Informationen',
  app_version: 'App-Version 0.10',
  match: 'Begegnung',
  matches: 'Begegnungen'
};
