# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'arnefeildtfb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for arnefeildtfb
  pod 'AppCenter/Push', '~> 1.5.0'
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTNetwork',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  platform :ios, '9.0'
  target 'arnefeildtfbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'arnefeildtfb-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for arnefeildtfb-tvOS

  target 'arnefeildtfb-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
