import { IStringsObject } from '.';
const pkg = require('../../../package.json');

const strings: IStringsObject = {
  ADD_TEAM: 'Weiteres Team hinzufügen',
  APP_VERSION: 'App-Version ' + pkg.version,
  ASSOCIATION: 'Organisation',
  AWAY: 'Gast',
  CANCEL: 'Abbrechen',
  CHANGE_DATE_INFO: ' um einen Termin zu akzeptieren.',
  CHANGE_MATCH_DATETIME: 'Termin ändern',
  CLASSIFICATION: 'Einstufung',
  CLUB: 'Verein',
  COMPETITIONS: 'Wettbewerbe',
  COMPETITIVE_INDEX: 'Leistungsindex',
  COMPETITIVE_INDEX_SHORT: 'LI',
  CONFIRM: 'Bestätigen',
  CONFIRM_DELETE_TEAM_MESSAGE:
    'Soll das Team "{{team}}" aus deiner Liste entfernt werden?',
  CONFIRM_DELETE_TEAM_TITLE: 'Team löschen?',
  CONTACT: 'Kontakt',
  DATETIME_SUGGESTIONS: 'Terminvorschläge',
  DELETE: 'Löschen',
  DOT_POSITION: '. Platz',
  DOT_SET: '. Satz',
  DRAW: 'Unentschieden',
  DRAW_POSTFIX: '',
  ENTER_ACCESS_DATA: 'Zugangsdaten eingeben',
  FIRST_MATCH: 'Hinspiel',
  GAMES: 'Spiele',
  GAMES_SHORT: 'Sp.',
  GAME_POINTS_POSITIV: 'SP+',
  GOALS: 'Tore',
  GROUP: 'Gruppe',
  GROUPS: 'Gruppen',
  HOME: 'Heim',
  HOME_MATCH_TIME: 'Heimspielzeit',
  HOME_TABLE: 'Heimtisch',
  HOME_VENUE: 'Heimspielort',
  INFORMATION: 'Informationen',
  INSERT_SCORE: 'Ergebnis eintragen',
  INTERNATIONAL_NUMBER: 'Internationale Spielernummer',
  LAST_DOUBLES: 'Letzte Doppel',
  LAST_SINGLES: 'Letzte Einzel',
  LEAGUES: 'Gruppen',
  LIVE: 'LIVE',
  LOGIN: 'Anmelden',
  LOGIN_ERROR: 'Fehler beim Anmelden. Überprüfe deine Zugangsdaten.',
  LOGIN_INFO:
    'Zugangsdaten für das Liga-Tool.\nWenn diese nicht eingetragen werden, können keine Spiele eingetragen werden.',
  LOGOUT: 'Abmelden',
  LOST: 'Niederlage',
  LOST_POSTFIX: 'n',
  MAIL_APP_NOT_FOUND: 'Keine E-Mail App gefunden.',
  MAPS_APP_NOT_FOUND: 'Keine Karten App gefunden.',
  MATCH: 'Begegnung',
  MATCHES: 'Begegnungen',
  MY_TEAM: 'Mein Team',
  NAME: 'Name',
  NATIONAL_NUMBER: 'Nationale Spielernummer',
  NEXT_MATCHES: 'Kommende',
  NO: 'Nein',
  NOTIFICATIONS: 'Benachrichtigungen',
  NOTIFICATION_END: 'Endstand',
  NOTIFICATION_LIVE: 'Live-Zwischenergebnis',
  NOTIFICATION_MATCH_DATE: 'Termin Änderungen',
  NOTIFICATION_SOUND: 'Sound/Vibration',
  NO_FIXTURES: 'Keine Begegnungen',
  NO_PLAYER_STATS: 'Keine Spielerstatistiken',
  NO_STANDING: 'Keine Tabelle',
  OPEN_VENUE: 'Spielort anzeigen',
  OVERVIEW: 'Übersicht',
  PARTICIPANTS: 'Meldungen',
  PASSWORD: 'Passwort',
  PAST_MATCHES: 'Vergangene',
  PHONE_APP_NOT_FOUND: 'Keine Telefon App gefunden.',
  PLAYER: 'Spieler',
  PLAYER_INFO: 'Spieler-Info',
  POINTS_SHORT: 'Pkt.',
  POSITION: 'Platz',
  PRESS_ON: 'Klicke auf ',
  RANKING: 'Rangliste',
  RANKINGS: 'Ranglisten',
  RANKING_POSITIONS: 'Ranglistenplatzierungen',
  RATE_SHORT: 'Q.',
  RESULT: 'Ergebnis',
  SAVE: 'Speichern',
  SCORE_BUTTON_TEXT: [
    'Ergebnis vorschlagen',
    'Ergebnis vorgeschlagen',
    'Ergebnis akzeptieren',
  ],
  SEASON: 'Saison',
  SECOND_HALFTIME: '2. Halbzeit',
  SELECT: 'Bitte wählen',
  SELECT_GROUP: 'Gruppe wählen',
  SELECT_GROUPS: 'Gruppen wählen',
  SELECT_NEXT_DATETIMTE: 'Weiteren Termin auswählen',
  SELECT_PLAYER: 'Spieler wählen',
  SELECT_TEAM: 'Team wählen',
  SELECT_TEAMS: 'Teams wählen',
  SETS: 'Sätze',
  SETTINGS: 'Einstellungen',
  SET_POINTS_RATE: 'Spielpunkte Quote',
  SET_UP: 'Einrichten',
  SKIP: 'Überspringen',
  SO_FAR: 'bisher ',
  STATISTIC: 'Statistik',
  STATISTICS: 'Statistiken',
  SUGGEST_DATETIMES: 'Termine vorschlagen',
  TABLE: 'Tabelle',
  TEAM: 'Team',
  TEAMS: 'Teams',
  TEAM_INFO: 'Team-Info',
  TIME_AT: 'um',
  TODAY: 'Heute',
  TOURNAMENT: 'Turnier',
  TOURNAMENT_PARTICIPATIONS: 'Turniermeldungen',
  UNCONFIRMED: 'Unbestätigt',
  USERNAME: 'Benutzername',
  USER_DATA: 'Benutzerdaten',
  WEEKDAYS: [
    'Sonntag',
    'Montag',
    'Dienstag',
    'Mittwoch',
    'Donnerstag',
    'Freitag',
    'Samstag',
  ],
  WELCOME_TEXT:
    'Im Folgenden kannst du nun die App einrichten. Wähle in den nächsten Schritten dein Teams aus, um alle Informationen auf einen Blick zu haben.',
  WIN: 'Sieg',
  WIN_POSTFIX: 'e',
  YES: 'Ja',
};

export default strings;
