import { IStringsObject } from '.';

const pkg = require('../../../package.json');

const strings: IStringsObject = {
  ADD_TEAM: 'Add a team',
  APP_VERSION: 'App version ' + pkg.version,
  ASSOCIATION: 'Organization',
  AWAY: 'Away',
  CANCEL: 'Cancel',
  CHANGE_DATE_INFO: ' to accept a date suggestion.',
  CHANGE_MATCH_DATETIME: 'Change date',
  CLASSIFICATION: 'Rank',
  CLUB: 'Club',
  COMPETITIONS: 'Competitions',
  COMPETITIVE_INDEX: 'Performance index',
  COMPETITIVE_INDEX_SHORT: 'PI',
  CONFIRM: 'Confirm',
  CONFIRM_DELETE_TEAM_MESSAGE: 'Remove team "{{team}}" from your list?',
  CONFIRM_DELETE_TEAM_TITLE: 'Delete team?',
  CONTACT: 'Contact',
  DATETIME_SUGGESTIONS: 'Date suggestions',
  DELETE: 'Delete',
  DOT_POSITION: '. place',
  DOT_SET: '. set',
  DRAW: 'Tie',
  DRAW_POSTFIX: 's',
  ENTER_ACCESS_DATA: 'Enter credentials',
  FIRST_MATCH: 'First leg match',
  GAMES: 'Games',
  GAMES_SHORT: 'G.',
  GAME_POINTS_POSITIV: 'GP+',
  GOALS: 'Goals',
  GROUP: 'Group',
  GROUPS: 'Groups',
  HOME: 'Home',
  HOME_MATCH_TIME: 'Playtime',
  HOME_TABLE: 'Home table',
  HOME_VENUE: 'Home location',
  INFORMATION: 'Information',
  INSERT_SCORE: 'Enter result',
  INTERNATIONAL_NUMBER: 'International player number',
  LAST_DOUBLES: 'Last doubles',
  LAST_SINGLES: 'Last singles',
  LEAGUES: 'Groups',
  LIVE: 'LIVE',
  LOGIN: 'Log in',
  LOGIN_ERROR:
    'Error while login. Please check your credentials and try again.',
  LOGIN_INFO:
    'Credentials for the "Liga-Tool". Results can only be entered with valid credentials.',
  LOGOUT: 'Log out',
  LOST: 'Loss',
  LOST_POSTFIX: 'es',
  MAIL_APP_NOT_FOUND: 'No mail app found.',
  MAPS_APP_NOT_FOUND: 'No map app found.',
  MATCH: 'Match',
  MATCHES: 'Matches',
  MY_TEAM: 'My Team',
  NAME: 'Name',
  NATIONAL_NUMBER: 'National player number',
  NEXT_MATCHES: 'Upcomming',
  NO: 'No',
  NOTIFICATIONS: 'Notifications',
  NOTIFICATION_END: 'Final score',
  NOTIFICATION_LIVE: 'Live score',
  NOTIFICATION_MATCH_DATE: 'Termin Änderungen',
  NOTIFICATION_SOUND: 'Sound/Vibration',
  NO_FIXTURES: 'No matches',
  NO_PLAYER_STATS: 'No player statistics',
  NO_STANDING: 'No standings',
  OPEN_VENUE: 'Show location',
  OVERVIEW: 'Overview',
  PARTICIPANTS: 'Participants',
  PASSWORD: 'Password',
  PAST_MATCHES: 'Past',
  PHONE_APP_NOT_FOUND: 'No phone app found.',
  PLAYER: 'Player',
  PLAYER_INFO: 'Player details',
  POINTS_SHORT: 'Pts.',
  POSITION: 'Place',
  PRESS_ON: 'Click on ',
  RANKING: 'Ranking',
  RANKINGS: 'Rankings',
  RANKING_POSITIONS: 'Ranking positions',
  RATE_SHORT: 'R.',
  RESULT: 'Result',
  SAVE: 'Save',
  SCORE_BUTTON_TEXT: ['Suggest result', 'Result suggested', 'Accept result'],
  SEASON: 'Season',
  SECOND_HALFTIME: '2nd half',
  SELECT: 'Please select',
  SELECT_GROUP: 'Select group',
  SELECT_GROUPS: 'Select groups',
  SELECT_NEXT_DATETIMTE: 'Select more dates',
  SELECT_PLAYER: 'Select player',
  SELECT_TEAM: 'Select team',
  SELECT_TEAMS: 'Select teams',
  SETS: 'Sets',
  SETTINGS: 'Settings',
  SET_POINTS_RATE: 'Gamepoints rate',
  SET_UP: 'Set up',
  SKIP: 'Skip',
  SO_FAR: 'So far ',
  STATISTIC: 'Statistic',
  STATISTICS: 'Statistics',
  SUGGEST_DATETIMES: 'Suggest dates',
  TABLE: 'Standings',
  TEAM: 'Team',
  TEAMS: 'Teams',
  TEAM_INFO: 'Team info',
  TIME_AT: 'at',
  TODAY: 'Current',
  TOURNAMENT: 'Tournament',
  TOURNAMENT_PARTICIPATIONS: 'Tournament participations',
  UNCONFIRMED: 'unconfirmed',
  USERNAME: 'Username',
  USER_DATA: 'User data',
  WEEKDAYS: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednsday',
    'Thursday',
    'Friday',
    'Saturday',
  ],
  WELCOME_TEXT:
    'Afterwards you can set up the app. In the next steps select your team to have all information at a glance.',
  WIN: 'Win',
  WIN_POSTFIX: 's',
  YES: 'Yes',
};

export default strings;
